game: "MiniGrid-SimpleCrossingS9N1-v0"
seed: 0  # this has precedence over subset
subset: 10  # 0 (false) or no of mazes used

train_steps: 1_000_000
test_steps: 15000

mem_size: 100_000
batch_size: 32
hist_len: 1

lr: 0.001
target_update: 1000
gamma: 0.95

epsilon_steps: 100_000
device: cuda
