_experiment_parameters:
  epsilon_steps: 100000
  gamma: 0.99
  lr: 0.0001
  target_update: 1000
cfg_id: 17
epsilon_steps: 100000
gamma: 0.99
lr: 0.0001
target_update: 1000
title: gamma=0.99; target_update=1000; lr=0.0001; epsilon_steps=100000
