_experiment_parameters:
  epsilon_steps: 100000
  gamma: 0.95
  lr: 0.0001
  target_update: 1000
cfg_id: 5
epsilon_steps: 100000
gamma: 0.95
lr: 0.0001
target_update: 1000
title: gamma=0.95; target_update=1000; lr=0.0001; epsilon_steps=100000
