_experiment_parameters:
  epsilon_steps: 100000
  gamma: 0.95
  lr: 0.001
  target_update: 10000
cfg_id: 9
epsilon_steps: 100000
gamma: 0.95
lr: 0.001
target_update: 10000
title: gamma=0.95; target_update=10000; lr=0.001; epsilon_steps=100000
