_experiment_parameters:
  epsilon_steps: 100000
  gamma: 0.99
  lr: 0.01
  target_update: 10000
cfg_id: 19
epsilon_steps: 100000
gamma: 0.99
lr: 0.01
target_update: 10000
title: gamma=0.99; target_update=10000; lr=0.01; epsilon_steps=100000
