_experiment_parameters:
  epsilon_steps: 10000
  gamma: 0.95
  lr: 0.01
  target_update: 10000
cfg_id: 6
epsilon_steps: 10000
gamma: 0.95
lr: 0.01
target_update: 10000
title: gamma=0.95; target_update=10000; lr=0.01; epsilon_steps=10000
