_experiment_parameters:
  epsilon_steps: 10000
  gamma: 0.99
  lr: 0.001
  target_update: 1000
cfg_id: 14
epsilon_steps: 10000
gamma: 0.99
lr: 0.001
target_update: 1000
title: gamma=0.99; target_update=1000; lr=0.001; epsilon_steps=10000
