
er:
  priority: [var, uni]
  alpha: [0.6, 1.0]
  beta: [null, 0.2, 0.4]
  bootstrap_args: [[-1, 0.5], [-1, 0.9]]

liftoff:
  - vars: [priority, er.alpha]
    "->": [[uni, delete]]
  - vars: [priority, er.beta]
    "->": [[uni, delete]]


