game: "MiniGrid-Dynamic-Obstacles-Random-6x6-v0"
# either an int or a number of random seeds, ex.: r10 or r5
# if seed: null then we train and test on all mdps.
seed: r5

train_steps: 2_000_000
test_steps: 30000

lin_size: 64

mem_size: 100_000
batch_size: 32
hist_len: 2


lr: 0.001
update_freq: 3
epsilon_steps: 100_000
gamma: 0.92
target_update: 500

device: cuda
