_experiment_parameters:
  hist_len: 2
  lin_size: 256
  mem_size: 100000
  target_update: 500
cfg_id: 41
hist_len: 2
lin_size: 256
mem_size: 100000
target_update: 500
title: hist_len=2; mem_size=100000; target_update=500; lin_size=256
