_experiment_parameters:
  hist_len: 2
  lin_size: 64
  mem_size: 10000
  target_update: 500
cfg_id: 30
hist_len: 2
lin_size: 64
mem_size: 10000
target_update: 500
title: hist_len=2; mem_size=10000; target_update=500; lin_size=64
