_experiment_parameters:
  hist_len: 3
  lin_size: 128
  mem_size: 100000
  target_update: 500
cfg_id: 67
hist_len: 3
lin_size: 128
mem_size: 100000
target_update: 500
title: hist_len=3; mem_size=100000; target_update=500; lin_size=128
