_experiment_parameters:
  hist_len: 1
  lin_size: 256
  mem_size: 10000
  target_update: 500
cfg_id: 5
hist_len: 1
lin_size: 256
mem_size: 10000
target_update: 500
title: hist_len=1; mem_size=10000; target_update=500; lin_size=256
