_experiment_parameters:
  hist_len: 1
  lin_size: 128
  mem_size: 10000
  target_update: 1000
cfg_id: 7
hist_len: 1
lin_size: 128
mem_size: 10000
target_update: 1000
title: hist_len=1; mem_size=10000; target_update=1000; lin_size=128
