_experiment_parameters:
  hist_len: 1
  lin_size: 64
  mem_size: 200000
  target_update: 1000
cfg_id: 24
hist_len: 1
lin_size: 64
mem_size: 200000
target_update: 1000
title: hist_len=1; mem_size=200000; target_update=1000; lin_size=64
