_experiment_parameters:
  hist_len: 3
  lin_size: 128
  mem_size: 100000
  target_update: 1000
cfg_id: 70
hist_len: 3
lin_size: 128
mem_size: 100000
target_update: 1000
title: hist_len=3; mem_size=100000; target_update=1000; lin_size=128
