_experiment_parameters:
  lin_size: 128
  mem_size: 200000
  target_update: 1000
cfg_id: 16
lin_size: 128
mem_size: 200000
target_update: 1000
title: mem_size=200000; target_update=1000; lin_size=128
