_experiment_parameters:
  hist_len: 2
  lin_size: 64
  mem_size: 10000
  target_update: 1000
cfg_id: 33
hist_len: 2
lin_size: 64
mem_size: 10000
target_update: 1000
title: hist_len=2; mem_size=10000; target_update=1000; lin_size=64
