_experiment_parameters:
  lin_size: 256
  mem_size: 200000
  target_update: 1000
cfg_id: 17
lin_size: 256
mem_size: 200000
target_update: 1000
title: mem_size=200000; target_update=1000; lin_size=256
