_experiment_parameters:
  hist_len: 3
  lin_size: 256
  mem_size: 200000
  target_update: 1000
cfg_id: 80
hist_len: 3
lin_size: 256
mem_size: 200000
target_update: 1000
title: hist_len=3; mem_size=200000; target_update=1000; lin_size=256
