_experiment_parameters:
  hist_len: 3
  lin_size: 128
  mem_size: 200000
  target_update: 100
cfg_id: 73
hist_len: 3
lin_size: 128
mem_size: 200000
target_update: 100
title: hist_len=3; mem_size=200000; target_update=100; lin_size=128
